fix:daskjadksljads

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -8,35 +8,40 @@ on:
 jobs:
   validate-commit-message:
     runs-on: ubuntu-latest
+    outputs:
+      commit_status: ${{ steps.filter-commit.outcome }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Check commit messages
+      - name: Filter merge commits
+        id: filter-commit
         run: |
           COMMIT_MSG=$(git show -s --format=%B)
-          if [[ "$COMMIT_MSG" =~ ^Merge\ pull\ request ]]; then
-            echo "Skipping merge commit."
-            echo "status=success" >> $GITHUB_ENV
+          if [[ "$COMMIT_MSG" =~ ^Merge ]]; then
+            echo "Merge commit detected. Skipping further actions."
+            exit 78  # Exiting with neutral status
           else
-            echo "Commit Message: $COMMIT_MSG"
-            KEYWORDS='["1","2","3"]'
-            URL_PATTERN='https://well-check.atlassian.net'
-            STATUS="fail"
-            if [[ "$COMMIT_MSG" =~ "fix" || "$COMMIT_MSG" =~ "feat" || "$COMMIT_MSG" =~ "chore" ]]; then
-              if [[ "$COMMIT_MSG" =~ $URL_PATTERN ]]; then
-                STATUS="success"
-              fi
-            fi
-            echo "status=$STATUS" >> $GITHUB_ENV
-            if [[ "$STATUS" == "fail" ]]; then
-              echo "Commit message validation failed."
-            fi
+            echo "Non-merge commit. Proceeding with checks."
+            exit 0  # Proceed with workflow
+
+      - name: Check commit messages
+        if: steps.filter-commit.outcome == 'success'
+        run: |
+          KEYWORDS='["1","2","3"]'
+          URL_PATTERN='https://well-check.atlassian.net'
+          COMMIT_MSG=$(git show -s --format=%B)
+          echo "Commit Message: $COMMIT_MSG"
+          if [[ ! "$COMMIT_MSG" =~ "fix" && ! "$COMMIT_MSG" =~ "feat" && ! "$COMMIT_MSG" =~ "chore" ]] || [[ ! "$COMMIT_MSG" =~ $URL_PATTERN ]]; then
+            echo "Commit message validation failed."
+            echo "status=fail" >> $GITHUB_ENV
+          else
+            echo "status=success" >> $GITHUB_ENV
 
   build-and-test:
     needs: validate-commit-message
+    if: needs.validate-commit-message.outputs.commit_status == 'success'
     runs-on: ubuntu-latest
-    if: env.status == 'success'
     steps:
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -61,24 +66,23 @@ jobs:
         run: npm run build
         continue-on-error: true
 
-      - name: Check for failures
-        id: check-failures
+      - name: Determine failed step
         run: |
-          FAILED_STEPS=""
-          [ ${{ steps.install.outcome }} != 'success' ] && FAILED_STEPS+="Install dependencies, "
-          [ ${{ steps.lint.outcome }} != 'success' ] && FAILED_STEPS+="Run lint, "
-          [ ${{ steps.test.outcome }} != 'success' ] && FAILED_STEPS+="Run tests, "
-          [ ${{ steps.build.outcome }} != 'success' ] && FAILED_STEPS+="Run build, "
-          echo "FAILED_STEPS=${FAILED_STEPS::-2}" >> $GITHUB_ENV
+          FAILED_STEP=""
+          [[ ${{ steps.install.outcome }} != 'success' ]] && FAILED_STEP="Install dependencies"
+          [[ ${{ steps.lint.outcome }} != 'success' ]] && FAILED_STEP="Run lint"
+          [[ ${{ steps.test.outcome }} != 'success' ]] && FAILED_STEP="Run tests"
+          [[ ${{ steps.build.outcome }} != 'success' ]] && FAILED_STEP="Run build"
+          echo "FAILED_STEP=$FAILED_STEP" >> $GITHUB_ENV
 
   comment-and-close:
     needs: [validate-commit-message, build-and-test]
+    if: env.status == 'fail' || env.FAILED_STEP != ''
     runs-on: ubuntu-latest
-    if: env.status == 'fail' || env.FAILED_STEPS != ''
     steps:
       - name: Leave comment on PR
         uses: peter-evans/create-or-update-comment@v4.0.0
         with:
           issue-number: ${{ github.event.pull_request.number }}
-          body: "Failed at steps: ${{ env.FAILED_STEPS }}"
+          body: "Failed at step: ${{ env.FAILED_STEP }}"
           reactions: '+1'
