fix:dsadsakl;dsak

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -24,25 +24,26 @@ jobs:
         id: check-commits
         run: |
           # 커밋 메시지 검사
-          echo "COMMIT_MSG=$(git log --no-merges -1 --oneline)" >> "$GITHUB_ENV"
+          echo "COMMIT_MSG=$(git log --no-merges -1 --oneline)" >> "$GITHUB_OUTPUT"
 
-          echo ${{env.COMMIT_MSG}}
+          echo ${{env.URL_PATTERN}}
+          echo ${{steps.check-commits.outputs.COMMIT_MSG}}
           
           # 키워드 확인
-          echo "STATUS_CHECK=fail" >> "$GITHUB_ENV"
+          echo "STATUS_CHECK=fail" >> "$GITHUB_OUTPUT"
           for keyword in "${KEYWORDS[@]}"; do
-            if [[ ${{env.COMMIT_MSG}} =~ $keyword: ]]; then
-              STATUS_CHECK=true
+            if [[ ${{steps.check-commits.outputs.COMMIT_MSG}} =~ $keyword: ]]; then
+              "STATUS_CHECK=true" >> "$GITHUB_OUTPUT"
               break
             fi
           done
 
-          if [ ${{env.STATUS_CHECK}} != true ]; then
+          if [ ${{steps.check-commits.outputs.STATUS_CHECK}} != true ]; then
             echo "message=Missing required keywords ( ${KEYWORDS} )." >> "$GITHUB_ENV"
             echo "status=fail" >> "$GITHUB_ENV"
           else
             # URL 검사
-            if ! [[ ${{env.COMMIT_MSG}} =~ $URL_PATTERN ]]; then
+            if ! [[ ${{steps.check-commits.outputs.COMMIT_MSG}} =~ $URL_PATTERN ]]; then
               echo "message=Commit message does not contain required URL." >> "$GITHUB_ENV"
               echo "status=fail" >> "$GITHUB_ENV"
             else
