Update pull-request.yml

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -23,26 +23,21 @@ jobs:
           URL_PATTERN='https://well-check.atlassian.net'
 
           echo "Commit Message: $COMMIT_MSG"
-          echo "URL Pattern: $URL_PATTERN"
           
           # Check individual conditions
-          if ! [[ $COMMIT_MSG =~ "fix" || $COMMIT_MSG =~ "feat" || $COMMIT_MSG =~ "chore" ]]; then
-            echo "Keyword condition failed."
-            echo "fix, feat, chore, refactor, hotfix 등 커밋 분류를 커밋메시지에 포함시켜주세요. " >> $GITHUB_STEP_SUMMARY
+          if ! [[ $COMMIT_MSG =~ fix|feat|chore|reafactor|hotfix ]]; then
+            echo "fix, feat, chore, refactor, hotfix 등 커밋 분류를 커밋메시지에 포함시켜주세요. \n" >> $GITHUB_STEP_SUMMARY
+            echo "outcome=fail" >> $GITHUB_OUTPUT
+            echo "PR_COMMIT_MSG=Keyword condition failed." >> $GITHUB_OUTPUT
           fi
           if ! [[ $COMMIT_MSG =~ $URL_PATTERN ]]; then
-            echo "지라 이슈를 링크 해주세요!" >> $GITHUB_STEP_SUMMARY
-          fi
-          
-
-          if [[ $COMMIT_MSG =~ fix|feat|chore ]] && [[ $COMMIT_MSG =~ $URL_PATTERN ]]; then
-            echo "outcome=success" >> $GITHUB_OUTPUT
-          else
-            echo "Commit message validation failed."
+            echo "지라 이슈를 링크 해주세요. \n" >> $GITHUB_STEP_SUMMARY
             echo "outcome=fail" >> $GITHUB_OUTPUT
+            echo "PR_COMMIT_MSG=issue is not contains this commit" >> $GITHUB_OUTPUT
           fi
           
           echo message=$(cat $GITHUB_STEP_SUMMARY) >> $GITHUB_OUTPUT
+          
           
       - name: Leave comment on PR
         if: steps.check-commit.outputs.outcome == 'fail' || failure()
@@ -56,4 +51,5 @@ jobs:
         uses: peter-evans/close-pull@v3
         with:
           pull-request-number: 1
+          comment: ${{steps.check-commit.outputs.PR_COMMIT_MSG}}
           delete-branch: false
